### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by sjanssen2** [biocore/gneiss#107]
I wanted to install gneiss as described in the Readme on barnacle. That is what happened. Is the readme still up to date?

barnacle x86_64 ~/>conda create -n gneiss_env python=3
barnacle x86_64 ~/>source activate gneiss_env
(gneiss_env) barnacle x86_64 ~/>conda install pyqt=4.11.4
Fetching package metadata .........
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt 4.11.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by sjanssen2** [comment]
looks like you need to be more specific:
conda create -n gneiss_env python=3.5
works for me

**Comment by mortonjt** [comment]
Have you tried python=3.5?

pyqt is known to have installation issues - another motivation for making
it an optional dependency.

**Comment by mortonjt** [comment]
The README has been updated, so this should be fixed.
