### ISSUE TITLE
Port pycogent drawing 

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#109]
Looks like pycogent has support for coloring trees
https://github.com/pycogent/pycogent/blob/master/cogent/draw/dendrogram.py

Combine this with bokeh, and we can have interactive trees
http://chuckpr.github.io/blog/trees2.html

**Comment by rob-knight** [comment]
That's a great idea! The cogent layout algorithms are pretty good and should include wedges etc, may need to backport some functionality from topiaryexplorer for algorithms for dynamic collapsing.

On Feb 2, 2017, at 6:24 PM, Jamie Morton <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like pycogent has support for coloring trees
https://github.com/pycogent/pycogent/blob/master/cogent/draw/dendrogram.py

Combine this with bokeh, and we can have interactive trees
http://chuckpr.github.io/blog/trees2.html

-
