### ISSUE TITLE
Weird extra label on heatmap

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#145]
![image](https://cloud.githubusercontent.com/assets/4184797/24177293/b82fe65e-0e5e-11e7-976f-9374d580753c.png)

The last label shouldn't be there.

**Comment by nbokulich** [comment]
I believe 6243 is the elevation for the bad "control" samples that were removed from the analysis. Perhaps these were left in the mapping file and that is somehow leading to the extra label? Sounds like a goofy idea to me but hope that helps diagnose...

**Comment by mortonjt** [comment]
:man_facepalming: that's definitely what's happening
