### ISSUE TITLE
tabulate taxa associated with top balances

### ISSUE THREAD

**Issue by nbokulich** [biocore/gneiss#181]
Most users will want to know what taxa are associated with each balance. You did some cool stuff with this on the Glen Canyon data for me, and I think that those would be useful standard-issue plots/tables.

Plotting collapsed taxa is great, but even just outputting a table (which can be downloaded as a csv) would be useful. Users should be able to specify:
1) taxonomic level at which taxa should be collapsed (or outputting individual SVs/OTUs associated with balances)
2) the number of top taxa to output (this is particularly relevant for plots)

**Comment by mortonjt** [comment]
Big :+1: . We do have a PR in the works [here](https://github.com/biocore/gneiss/pull/172) meant to address this.  Let me touch that up - I'd definitely be curious to hear your thoughts on how to improve it!

**Comment by mortonjt** [comment]
This has been addressed in #172
