### ISSUE TITLE
import error for fresh conda env

### ISSUE THREAD

**Issue by sjanssen2** [biocore/gneiss#191]
I just set up a new conda env for gneiss:
`conda create -n gneiss_env gneiss python=3.5 -c biocore -c qiime2`
and additionally installed jupyter in that env.

the single command in an otherwise empty notebook `import gneiss` results in the following error:
```ImportError                               Traceback (most recent call last)
<ipython-input-1-01afee2b7699> in <module>()
----> 1 import gneiss

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.1.0-py3.5.egg/gneiss/__init__.py in <module>()
      9 from __future__ import absolute_import, division, print_function
     10 
---> 11 from gneiss._formula import mixedlm, ols
     12 
     13 __all__ = ['ols', 'mixedlm']

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.1.0-py3.5.egg/gneiss/_formula.py in <module>()
      8 import numpy as np
      9 import pandas as pd
---> 10 import statsmodels.formula.api as smf
     11 from skbio.stats.composition import ilr
     12 from gneiss.util import match, match_tips, rename_internal_nodes

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/formula/api.py in <module>()
----> 1 from statsmodels.regression.linear_model import GLS
      2 gls = GLS.from_formula
      3 from statsmodels.regression.linear_model import WLS
      4 wls = WLS.from_formula
      5 from statsmodels.regression.linear_model import OLS

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/regression/__init__.py in <module>()
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels import NoseWrapper as Tester
      4 test = Tester().test

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/regression/linear_model.py in <module>()
     50                                           cache_readonly,
     51                                           cache_writable)
---> 52 import statsmodels.base.model as base
     53 import statsmodels.base.wrapper as wrap
     54 from statsmodels.emplike.elregress import _ELRegOpts

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/model.py in <module>()
      3 import numpy as np
      4 from scipy import stats
----> 5 from statsmodels.base.data import handle_data
      6 from statsmodels.tools.tools import recipr, nan_dot
      7 from statsmodels.stats.contrast import ContrastResults

~/miniconda3/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/data.py in <module>()
      6 from statsmodels.compat.numpy import np_matrix_rank
      7 import numpy as np
----> 8 from pandas import DataFrame, Series, TimeSeries, isnull
      9 from statsmodels.tools.decorators import (resettable_cache, cache_readonly,
     10                                           cache_writable)

ImportError: cannot import name 'TimeSeries'```

**Comment by mortonjt** [comment]
Hmm.  That looks like a statsmodels incompatibility with pandas released 4
days ago.

https://github.com/pandas-dev/pandas/releases

For now, I'd downgrade pandas to 0.19 - but we'll need to fix this in the
conda recipe for the beta release next week.

**Comment by adityabandla** [comment]
Hi

I am trying to run the tutorial datasets. However, upon installing gneiss through conda, I get the following error

ImportError: No module named 'skbio.metadata._intersection'

skbio seems to be installed though

**Comment by mortonjt** [comment]
Could you provide the contents of the following output?

`conda env export `

**Comment by adityabandla** [comment]
Hi Jamie

name: gneiss_env
channels:
- conda-forge
- anaconda
- qiime2
- qiime2/label/2017.5
- biocore
- bioconda
- defaults
dependencies:
- pandas=0.19.2=np112py35_1
- bioconductor-biobase=2.34.0=r3.3.1_0
- bioconductor-biocgenerics=0.20.0=r3.3.1_0
- bioconductor-biocparallel=1.6.6=r3.3.1_0
- bioconductor-biostrings=2.42.1=r3.3.1_0
- bioconductor-dada2=1.4.0=r3.3.1_0
- bioconductor-genomeinfodb=1.10.3=r3.3.1_0
- bioconductor-genomicalignments=1.8.4=r3.3.1_0
- bioconductor-genomicranges=1.26.4=r3.3.1_0
- bioconductor-iranges=2.8.2=r3.3.1_0
- bioconductor-rsamtools=1.24.0=r3.3.1_0
- bioconductor-s4vectors=0.12.2=r3.3.1_0
- bioconductor-shortread=1.32.0=r3.3.1_0
- bioconductor-summarizedexperiment=1.2.3=r3.3.1_0
- bioconductor-xvector=0.14.1=r3.3.1_0
- bioconductor-zlibbioc=1.20.0=r3.3.1_0
- blast=2.6.0=boost1.60_0
- fasttree=2.1.9=1
- mafft=7.221=0
- r-futile.logger=1.4.1=r3.3.1_0
- r-futile.options=1.0.0=r3.3.1_0
- r-hwriter=1.3.2=r3.3.1_0
- r-lambda.r=1.1.7=r3.3.1_0
- r-rcppparallel=4.3.20=r3.3.1_1
- r-snow=0.4_1=r3.3.1_0
- scikit-bio=0.4.2=np112py35_0
- sortmerna=2.0=1
- vsearch=2.0.3=1
- deblur=1.0.2=py35_0
- gneiss=0.1.0=py35_0
- emperor=1.0.0beta8=py35_2
- appnope=0.1.0=py35_0
- bleach=1.5.0=py35_0
- bokeh=0.12.5=py35_1
- bz2file=0.98=py35_0
- cachecontrol=0.11.7=py35_0
- click=6.7=py35_0
- contextlib2=0.5.5=py35_0
- curl=7.52.1=0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_1
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- future=0.16.0=py35_1
- glib=2.50.2=1
- gsl=2.2.1=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np112py35_0
- hdf5=1.8.17=1
- html5lib=0.999=py35_0
- icu=54.1=0
- ipykernel=4.6.1=py35_0
- ipython=6.0.0=py35_1
- ipython_genutils=0.2.0=py35_0
- ipywidgets=6.0.0=py35_0
- jbig=2.1=0
- jedi=0.10.2=py35_2
- jinja2=2.9.6=py35_0
- jpeg=9b=0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.0.1=py35_0
- jupyter_core=4.3.0=py35_0
- libffi=3.2.1=1
- libgcc=4.8.5=1
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- lockfile=0.12.2=py35_0
- markupsafe=0.23=py35_2
- matplotlib=2.0.2=np112py35_0
- mistune=0.7.4=py35_0
- mkl=2017.0.1=0
- natsort=5.0.3=py35_0
- nbconvert=5.1.1=py35_0
- nbformat=4.3.0=py35_0
- ncurses=5.9=10
- nose=1.3.7=py35_1
- notebook=5.0.0=py35_0
- numpy=1.12.1=py35_0
- openssl=1.0.2l=0
- pandocfilters=1.4.1=py35_0
- path.py=10.3.1=py35_0
- patsy=0.4.1=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.14=py35_0
- psutil=5.2.2=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2017.2=py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=4
- r=3.3.1=r3.3.1_0
- r-base=3.3.1=0
- r-bh=1.60.0_2=r3.3.1_0
- r-bitops=1.0_6=r3.3.1_2
- r-boot=1.3_18=r3.3.1_0
- r-chron=2.3_47=r3.3.1_0
- r-class=7.3_14=r3.3.1_0
- r-cluster=2.0.4=r3.3.1_0
- r-codetools=0.2_14=r3.3.1_0
- r-colorspace=1.2_6=r3.3.1_0
- r-data.table=1.9.6=r3.3.1_0
- r-dichromat=2.0_0=r3.3.1_2
- r-digest=0.6.9=r3.3.1_0
- r-foreign=0.8_66=r3.3.1_0
- r-ggplot2=2.1.0=r3.3.1_0
- r-gtable=0.2.0=r3.3.1_0
- r-kernsmooth=2.23_15=r3.3.1_0
- r-labeling=0.3=r3.3.1_2
- r-lattice=0.20_33=r3.3.1_0
- r-latticeextra=0.6_28=r3.3.1_0
- r-magrittr=1.5=r3.3.1_2
- r-mass=7.3_45=r3.3.1_0
- r-matrix=1.2_6=r3.3.1_0
- r-mgcv=1.8_12=r3.3.1_0
- r-munsell=0.4.3=r3.3.1_0
- r-nlme=3.1_128=r3.3.1_0
- r-nnet=7.3_12=r3.3.1_0
- r-plyr=1.8.4=r3.3.1_0
- r-rcolorbrewer=1.1_2=r3.3.1_3
- r-rcpp=0.12.5=r3.3.1_0
- r-rcurl=1.95_4.8=r3.3.1_0
- r-recommended=3.3.1=r3.3.1_0
- r-reshape2=1.4.1=1a
- r-rpart=4.1_10=r3.3.1_0
- r-scales=0.4.0=r3.3.1_0
- r-spatial=7.3_11=r3.3.1_0
- r-stringi=1.1.1=r3.3.1_0
- r-stringr=1.0.0=r3.3.1_0
- r-survival=2.39_4=r3.3.1_0
- readline=6.2=2
- requests=2.14.2=py35_0
- scikit-learn=0.18.1=np112py35_1
- scipy=0.19.0=np112py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np112py35_0
- terminado=0.6=py35_0
- testpath=0.3=py35_0
- tk=8.5.18=0
- tornado=4.5.1=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=2.0.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- biom-format=2.1.5=py35_3
- ijson=2.3=py35_0
- tzlocal=1.3=py35_0
- q2-alignment=2017.5.0=py35_0
- q2-composition=2017.5.0=py35_0
- q2-dada2=2017.5.0=py35_0
- q2-deblur=2017.5.0=py35_0
- q2-demux=2017.5.0=py35_0
- q2-diversity=2017.5.0=py35_0
- q2-emperor=2017.5.0=py35_0
- q2-feature-classifier=2017.5.0=py35_0
- q2-feature-table=2017.5.0=py35_0
- q2-phylogeny=2017.5.0=py35_0
- q2-quality-filter=2017.5.0=py35_0
- q2-taxa=2017.5.0=py35_0
- q2-types=2017.5.0=py35_0
- q2cli=2017.5.0=py35_0
- q2templates=2017.5.0=py35_0
- qiime2=2017.5.0=py35_0
- pip:
  - ete3==3.0.0b35
  - ipython-genutils==0.2.0
  - jupyter==1.0.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - qtconsole==4.3.0

**Comment by mortonjt** [comment]
Alrighty - looks like an old version of scikit-bio is installed.  Gneiss requires the most up to date version of scikit-bio.

You should be able to install that via
`conda install scikit-bio`

I'm going to keep this issue open until the beta release -- since we need verify that the conda recipe is downloading the correct scikit-bio version.

**Comment by adityabandla** [comment]
The error popped up with the latest scikit version downloaded according to the conda recipe

I was playing around with the versions to see if it solved the error and hence the older version in the export command

However, even after updating to the latest version again, there seems to be a series of errors popping up. First was ImportError: No module named 'matplotlib._path'. So I updated matplotlib from the conda channels, then I got the error

ImportError: miniconda3/envs/gneiss_env/lib/python3.5/site-packages/biom_format-2.1.5-py3.5-macosx-10.6-x86_64.egg/biom/_filter.cpython-35m-darwin.so: invalid ELF header

So I tried installing gneiss in my qiime2 environment, but was unsuccessful

UnsatisfiableError: The following specifications were found to be in conflict:
  - gneiss
  - q2-deblur -> q2-types ==2017.2.0
  - q2-deblur -> q2cli ==2017.2.0
  - q2-deblur -> qiime2 ==2017.2.0

**Comment by adityabandla** [comment]
Installing gneiss via conda create -n gneiss_env gneiss python=3.5 -c biocore still seems to install only scikit-bio 0.4.2

**Comment by adityabandla** [comment]
Also, I can see certain dependencies on q2-2017.2, the conda recipe for this version of qiime is broken. It would be good if the dependencies point to the latest version q2-2017.5

**Comment by mortonjt** [comment]
This has been fixed in the beta release - let me know if this works
