### ISSUE TITLE
Decoupled tutorial or QIIME1-based tutorial?

### ISSUE THREAD

**Issue by adityabandla** [biocore/gneiss#193]
Hi Jamie

I have had a frustrating time since the weekend getting GNEISS to work with QIIME2. Can GNEISS be delinked from QIIME2?

Best,
Aditya

**Comment by mortonjt** [comment]
I'm putting this on the milestone for version 1.  Once we have the qiime2 / gneiss APIs in a more stable condition, it'll be more straightforward on how to do this.

**Comment by mortonjt** [comment]
This has been fixed in #214 .  Thanks for raising this @adityabandla !  You should see these changes in the next release once the conda release is out.
