### ISSUE TITLE
Additional ETE layouts

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#23]
- [ ] Edge weight coloration.  Similar to as shown in [Edge PCA](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0056859)
- [ ] Heatmaps linked to ETE
- [ ] Subtree collapsing / coloring.  Similar to the recent [tree of life paper](http://www.nature.com/articles/nmicrobiol201648).

**Comment by jhcepas** [comment]
probably you are aware of the following issues, but just in case: 

- Heatmaps and edge colors should be easy to implement in ETE. There are two options: building a heatmap matrix from scratch using basic shapes, or using the ProfileFace instance. In any case, there are some easy improvements that I always wanted to add, so this might be a good moment for that.
- Subtree collapsing is also possible using node.img_style['draw_descendants']=False  
- Background coloring of clades is also possible, although with a different style as in the tree of life paper.

**Comment by mortonjt** [comment]
Oh awesome!  I didn't know about the `node.img_typre['draw_descendants']=False` feature.
That will warrant some tinkering.

**Comment by mortonjt** [comment]
@jhcepas I have just added a PR for creating heatmaps in #87.  There were some features I found scattered across the ETE google groups (i.e. matplotlib colormaps).  Were these the sort of features that you were considering adding into ETE?

**Comment by mortonjt** [comment]
Concerning the subtree collapsing, how difficult would it be to replace the collapse node faces with polygons?  It would be really cool if it is possible to replace the internal nodes with triangles, rectangles ... that were approximately shaped to be the size of the original clade.  

Like in the tree of life figure, the large, long clades had some colored shapes that encapsulated tips of the tree.

**Comment by jhcepas** [comment]
Yes, it would be great to extend the gallery of predefined layouts. Could I take your layout function and add it to ETE's base code? 

Re collapsing nodes: Not difficult, as you have discovered already :) I would suggest expanding the faces module with whatever new items are required, and then used them as "branch-right" faces in collapsed nodes.

**Comment by mortonjt** [comment]
@jhcepas that would be awesome!  I just added the DiamondItem into this [PR](https://github.com/etetoolkit/ete/pull/251).

Note that the collapse functionality is a little clunky - it will require some user tweaking via the `breadth_scaling` and `depth_scaling` to tweak how much the diamonds should be scaled.  It would be awesome if these parameters could be completely ditched.  It is possible to calculate the pixel positions of all of the nodes before they are rendered?  That sort of information could probably be used to resolve.

**Comment by rob-knight** [comment]
You might want to look at TopiaryExplorer for examples of how we have done this in past (beware: Java...)

On Jan 10, 2017, at 9:14 AM, Jamie Morton <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhcepas<https://github.com/jhcepas> that would be awesome! I just added the DiamondItem into this PR<https://github.com/etetoolkit/ete/pull/251>.

Note that the collapse functionality is a little clunky - it will require some user tweaking via the breadth_scaling and depth_scaling to tweak how much the diamonds should be scaled. It would be awesome if these parameters could be completely ditched. It is possible to calculate the pixel positions of all of the nodes before they are rendered? That sort of information could probably be used to resolve.

-
