### ISSUE TITLE
Taxonomy summarization

### ISSUE THREAD

**Issue by tanaes** [biocore/gneiss#24]
Summarize subtree taxonomies of a given balance to aid interpretation

**Comment by jhcepas** [comment]
Could you elaborate on this? Not sure what's the goal, but I suspect it has to do with taxonomic names for internal branches?

If so, the NCBITaxa instance in [ete3 could help](http://etetoolkit.org/docs/latest/reference/reference_phylo.html#ete3.PhyloNode.annotate_ncbi_taxa). There are a couple of functions that will read the taxID associated to tip nodes and will annotate the whole tree, finding the species lineages and annotating internal branch with taxonomic names.

Once the tree is taxonomically annotated, the viz layout can read the annotations and output something like this: 
![image](https://cloud.githubusercontent.com/assets/163658/20921344/e8be32c0-bba3-11e6-86b6-9cb4c1a4a26a.png)

**Comment by wasade** [comment]
@jhcepas, is that just using LCA? If so, might be worth using tax2tree here which uses the f-measure and handles inconsistencies reasonably well.

**Comment by jhcepas** [comment]
yes, those annotations are strictly based on the NCBI topology. Ranks and scientific names of internal branches are based on the last shared item between the descendants lineage strings.

**Comment by mortonjt** [comment]
@tanaes What do you think about having taxonomic summaries like this?

![picture1](https://cloud.githubusercontent.com/assets/4184797/24075846/978acaa2-0be0-11e7-8236-06a402f1c9f7.png)

**Comment by mortonjt** [comment]
Note that we have somewhat addressed this in https://github.com/biocore/gneiss/pull/156.  But it would be nice if we could have interactive word clouds to summarize the contents of the features within each subtree.

**Comment by amnona** [comment]
maybe you can use the wordcloud package i used in dbbact (
https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py)
it outputs to a figure :)
easy to use, but not interactive

**Comment by mortonjt** [comment]
This has been addressed by #173
