### ISSUE TITLE
ImportError: cannot import name 'balanceplot'

### ISSUE THREAD

**Issue by jolespin** [biocore/gneiss#261]
It doesn't look like `balanceplot` is available in `0.4.4`
```python
import sys
print(sys.version)
import gneiss
print(gneiss.__version__)
from gneiss.balances import balance_basis
print("imported balance_basis")
from gneiss.balances import balanceplot
print("imported balanceplot")

# 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
# [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
# 0.4.4
# imported balance_basis
# ---------------------------------------------------------------------------
# ImportError                               Traceback (most recent call last)
# <ipython-input-3-cc7d36614c99> in <module>()
#       5 from gneiss.balances import balance_basis
#       6 print("imported balance_basis")
# ----> 7 from gneiss.balances import balanceplot
#       8 print("imported balanceplot")

# ImportError: cannot import name 'balanceplot'
```
![image](https://user-images.githubusercontent.com/9061708/42108848-92eee174-7b90-11e8-8d1c-09ed61075689.png)

**Comment by mortonjt** [comment]
That's correct - we removed this functionality a couple of releases ago.  We have replaced this with the [`radialplot`](https://github.com/biocore/gneiss/blob/master/gneiss/plot/_radial.py#L16)

Probably should remove update that notebook.
More plotting capabilities to come in next couple of months with [empress](https://github.com/biocore/empress)!

**Comment by Learnerhua** [comment]
Hello, I meet the same question when I run the commad from the tutorial https://github.com/biocore/gneiss/blob/master/ipynb/balance_trees.ipynb ,and I check the balance.py file without founding the module called balanceplot, So could you tell what should I do to run the command successfully?
Looking forward to hearing from you soon, THANKS

**Comment by Learnerhua** [comment]
> Hello, I meet the same question when I run the commad from the tutorial https://github.com/biocore/gneiss/blob/master/ipynb/balance_trees.ipynb ,and I check the balance.py file without founding the module called balanceplot, So could you tell what should I do to run the command successfully?
> Looking forward to hearing from you soon, THANKS

**Comment by mortonjt** [comment]
Not sure how I missed this -- see this issue : https://github.com/biocore/gneiss/issues/261
