### ISSUE TITLE
Update the pip and bioconda version 0.4.4 to require skbio ≥ 0.5.1 instead of == 0.5.1

### ISSUE THREAD

**Issue by jolespin** [biocore/gneiss#277]
Can you update these? Right now the pip installation and the bioconda build requires an old version of skbio.

**Comment by mortonjt** [comment]
Yes.

**Comment by mortonjt** [comment]
fyi - pypi is now up. https://pypi.org/project/gneiss/

bioconda recipe is coming up. https://github.com/bioconda/bioconda-recipes/pull/16165

**Comment by mortonjt** [comment]
@jolespin , I'm going to close this. If you experience any further issues, please reopen.
