### ISSUE TITLE
ImportError: cannot import name 'balanceplot'

### ISSUE THREAD

**Issue by Learnerhua** [biocore/gneiss#296]
Hello, I meet the "**ImportError: cannot import name 'balanceplot' from 'gneiss.balances**'"question when I run the commad from the tutorial https://github.com/biocore/gneiss/blob/master/ipynb/balance_trees.ipynb ,and I checked the balance.py file without finding the module called balanceplot, So what should I do to run the command successfully?
THANKS

**Comment by mortonjt** [comment]
Hi, thank you for your interest.  We have dropped support for ete3 in favor of [empress](https://github.com/biocore/empress).  But the ete3 visualizations can be accessed in the beta release

https://github.com/biocore/gneiss/tree/v0.4.0

**Comment by Learnerhua** [comment]
Problem solved.
Thank you very much !
