### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#63]
I personally find it really frustrating when I drop a couple of hours to build a regression model, only to realize that it was initialized with the wrong types.

For example, consider a variable like `Age` is actually a numerical value, but is represented as an object (i.e. string).

It would be nice to have some sort of type checking on the fly, maybe even taking advantage of PY3 types and/or the [categorical](http://pandas.pydata.org/pandas-docs/stable/categorical.html) / [numerical](http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.to_numeric.html) types in pandas.

Not sure about what the best approach here is ...

**Comment by antgonza** [comment]
This is something we used to do in Qiita to create our tables and I think is a good place to look if you want to do this. These are the 2 most important methods for this functionality: [get_datatypes](https://github.com/biocore/qiita/blob/v0.2.0/qiita_db/metadata_template/util.py#L71) &
[as_python_types](https://github.com/biocore/qiita/blob/v0.2.0/qiita_db/metadata_template/util.py#L55).

**Comment by mortonjt** [comment]
Awesome!!  That actually may do the trick

**Comment by mortonjt** [comment]
We have resolved this issue using this [function](https://github.com/biocore/gneiss/blob/master/gneiss/util.py#L273).
Thanks for the feedback @antgonza !
