### ISSUE TITLE
Add support for Principal Balance Analysis

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#70]
- [x] Hierarchical clustering via proportionality
- [ ] Sparse Principle Balances via sparse approximation on ilr PCA

http://congress.cimne.com/codawork11/Admin/Files/FilePaper/p55.pdf
http://www.elib.bsu.by/bitstream/123456789/51958/1/173-176.pdf

**Comment by ElDeveloper** [comment]
:+1:

**Comment by mortonjt** [comment]
We aren't going to add in the sparse principal balances.  The ward hierarchical clustering for the principal balances have been added.  So I'm going to close this issue for now.  

However, we will want to add in more principal balance methods to perform clustering wrt partial least squares, PCA and other methods involving orthonormal bases
