### ISSUE TITLE
qiime2 plugin

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#81]
This plugin can be found [here](https://github.com/mortonjt/q2-gneiss).  It would be great to knock this out by the beta release.

cc @gregcaporaso to give an idea about the latest possible deadline to have a q2 plugin for the beta version release.

**Comment by gregcaporaso** [comment]
@mortonjt, the beta release of QIIME 2 is planned for summer 2017.

**Comment by mortonjt** [comment]
Awesome!  That lines up nicely with the two milestones that have been put in place.  Thanks!

**Comment by mortonjt** [comment]
This has been integrated.
